### ISSUE TITLE
module _curses not found

### ISSUE THREAD

**Issue by hesanf** [vfarid/cf-ip-scanner-py#20]
Traceback (most recent call last):
  File "C:\Users\Hes\Desktop\cf-ip-scanner-py-1.5\start.py", line 14, in <module>
    import curses
  File "C:\Users\Hes\AppData\Local\Programs\Python\Python311\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by SinShino** [comment]
c:\Users\MYDESKTOP\Downloads\cf-ip-scanner-py-1.5                                                                   
λ py start.py                                                                                                       
Traceback (most recent call last):                                                                                  
  File "c:\Users\MYDESKTOP\Downloads\cf-ip-scanner-py-1.5\start.py", line 14, in <module>                           
    import curses                                                                                                   
  File "C:\Users\MYDESKTOP\AppData\Local\Programs\Python\Python311\Lib\curses\__init__.py", line 13, in <module>    
    from _curses import *                                                                                           
ModuleNotFoundError: No module named '_curses'

**Comment by iran-free-net** [comment]
In **Windows environment** you need to install curses package with the following command:

```
py -m pip install windows-curses
```

**Comment by zoheirkabuli** [comment]
> In **Windows environment** you need to install curses package with the following command:
> 
> ```
> py -m pip install windows-curses
> ```

thanks
it works
