### ISSUE TITLE
cf-ipv4.txt File Not Fond!

### ISSUE THREAD

**Issue by AbbasVB** [vfarid/cf-ip-scanner-py#8]
سلام
در زمان اجرای اسکریپت این فایل cf-ipv4.txt رو بازم داره که ارور می ده

**Comment by RimAzer** [comment]
سلام
ای خطا رو میده :
PS C:\Users\RAR\Desktop\cf-ip-scanner-py-1.4> py .\start.py
Traceback (most recent call last):
  File "C:\Users\RAR\Desktop\cf-ip-scanner-py-1.4\start.py", line 14, in <module>
    import curses
  File "C:\Users\RAR\AppData\Local\Programs\Python\Python310\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by vfarid** [comment]
Fixed in v1.5 and main branch
