### ISSUE TITLE
No module named '_curses'

### ISSUE THREAD

**Issue by RimAzer** [vfarid/cf-ip-scanner-py#9]
سلامتوی ورژن 1.3 بدون مشکل کار میکنه اما توی ورژن 1.4 خطا زیر رو میدهد 
PS C:\Users\RAR\Desktop\cf-ip-scanner-py-1.4> py .\start.py
Traceback (most recent call last):
  File "C:\Users\RAR\Desktop\cf-ip-scanner-py-1.4\start.py", line 14, in <module>
    import curses
  File "C:\Users\RAR\AppData\Local\Programs\Python\Python310\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by RimAzer** [comment]
دوستانی که مشکل بالا را دارند دستور زیر را در ترمینال بزنند تا این windows-curses نصب بشه و مشکل برطرف بشه.
pip install windows-curses
